# Generated by Django 5.2.3 on 2025-06-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Time in minutes to cook the recipe", null=True
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="preparation_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time in minutes to prepare the ingredients",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Average rating out of 5.0",
                max_digits=3,
                null=True,
            ),
        ),
    ]
