# Generated by Django 5.2.3 on 2025-06-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_recipe_cooking_time_recipe_preparation_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="process",
            field=models.TextField(
                blank=True,
                help_text="Step-by-step process to prepare the recipe",
                null=True,
            ),
        ),
    ]
