# Generated by Django 5.2.3 on 2025-07-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_cartitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="price",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
        ),
    ]
