# Generated by Django 5.2.3 on 2025-08-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_alter_cartitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
