# Generated by Django 5.2.3 on 2025-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_recipe_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
